### ISSUE TITLE
\\u0000 cannot be converted to text

### ISSUE THREAD

**Issue by SCdF** [medic/medic-webapp#2426]
While testing syncing a 0.4 CouchDB install I got this error. The whole error (phone number removed) is:

```
Something went wrong at Wed Jun 22 2016 18:56:56 GMT+0000 (UTC) { [error: unsupported Unicode escape sequence]
  name: 'error',
  length: 203,
  severity: 'ERROR',
  code: '22P05',
  detail: '\\u0000 cannot be converted to text.',
  hint: undefined,
  position: '35',
  internalPosition: undefined,
  internalQuery: undefined,
  where: 'JSON data, line 1: ...":{"secret":"","from":"<APHONENUMBER>","message":...',
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'json.c',
  line: '832',
  routine: 'json_lex_string' }
```

**Comment by SCdF** [comment]
This is because some SMS (for some reason) have \u0000 in them, which is not supported by PostgreSQL: https://www.postgresql.org/message-id/E1YHHV8-00032A-Em@gemulon.postgresql.org

It's not completely clear how the old code worked in this regard. I can't find the specific failing document in the production postgresql DB, so I'm guessing it simply failed to import it and moved on.

**Comment by SCdF** [comment]
Hey @estellecomment, check out my amazing escaping stills

**Comment by estellecomment** [comment]
Well escaped, sir

(I can't comment on non-diffed code but the comment l.21 is not so clear, it says what the function doesn't do, but not what it does! https://github.com/medic/medic-analytics/commit/2d295a027dc187dcf1b55889decbf526120b19c3#diff-ff87a94f73c3d23f6ab08c36ad30426eR21)

**Comment by SCdF** [comment]
It looks like we should fix this for 0.0.3 (the current prod version), so I have done so in the above commit.

**Comment by michaelkohn** [comment]
We installed the 0.0.4 branch last week and the error went away, but it showed up again over the weekend for that same project (I can't tell the exact time it started again).  The only difference I can really see between this error and the one above is the `length` and `position`.  The `position` on this one is quite a large number compared to above.

<pre><code>Starting import at Mon Jul 04 2016 20:42:11 GMT+0000 (UTC)
Import errored at Mon Jul 04 2016 20:42:47 GMT+0000 (UTC)
{ [error: unsupported Unicode escape sequence]
  name: 'error',
  length: 207,
  severity: 'ERROR',
  code: '22P05',
  detail: '\\u0000 cannot be converted to text.',
  hint: undefined,
  position: '318234',
  internalPosition: undefined,
  internalQuery: undefined,
  where: 'JSON data, line 1: ...":{"secret":"","from”:”<APHONENUMBER>“,”message":...',
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'json.c',
  line: '832',
  routine: 'json_lex_string' }
Next run at Mon Jul 04 2016 20:57:11 GMT+0000 (UTC)</code></pre>

**Comment by SCdF** [comment]
@michaelkohn well uhm hmmm, that's unfortunate.

The position is suspiciously high, and Javascript is a suspiciously terrible language some times. I am wondering if my replacement method only scans so far in? I'm have a play around and see if I can work it out.

**Comment by SCdF** [comment]
@michaelkohn so nothing obvious is jumping out at me: I fixed this issue in 1.0 and backported it to 0.0.3: is there a reason, if I tag the codebase soon, that this client cannot move to 1.0?

**Comment by SCdF** [comment]
@michaelkohn where did we get to with this? Is this still a problem?

**Comment by michaelkohn** [comment]
From what I can tell, it's not an issue on the new version of the adapter... I say this because the partnername_test DB (at time of writing) has 74,860 records in the couchdb table and if I go to https://partnername.app.medicmobile.org/_couch/_utils/index.html, I see the same number in the medic DB.... So I have to think it is working fine.  It's still failing on the old version but I'm fine not wasting any time trying to fix that because I'd like to migrate them this week sometime anyway.
