### ISSUE TITLE
Allow users to enter Bikram Sambat dates in Enketo forms on Android phones

### ISSUE THREAD

**Issue by sglangevin** [medic/medic-webapp#3513]
The date widget available in Enketo currently supports only the Gregorian calendar. In order to support facility-based users in our Nepal deployments, nurses using the web app need to be able to enter dates using the Bikram Sambat calendar. Make it possible for Enketo forms to display a widget that allows Bikram Sambat date entry.

cc @ranjuts @bishwas-medic

Related: #3404, #3405

**Comment by sglangevin** [comment]
More info from @ranjuts:
- Option to enter date in Nepali Date (Bikram Sambat) format : DD/MM/YYYY or pick from calendar (display Bikram Sambat Calendar  in date picker)

**Comment by ranjuts** [comment]
Had a chat w Alex re this and here's the gist. @alxndrsn please add/correct if anything. 

**Best option in terms of LOE + usability:** 3 separate dropdowns for DD, MM (name of month) and YY. Typing the date would be the default option. For month, when typing enter as integer but display the name of month in text once done entering (eg: Baisakh, Jetha, Asar etc or बैशाख, जेठ, असार  if form language is Nepali). 

**Best option in terms of usability:** 3 separate dropdowns for DD, MM (name of month) and YY. Typing the date would be the default option. For month, when typing enter as integer but display name of month in text once done entering (eg: Baisakh, Jetha, Asar etc or बैशाख, जेठ, असार etc if form language is Nepali). 
AND 
Pick from Bikram Sambat Calendar. User has the option to choose.

**Comment by sglangevin** [comment]
I'm going to bump this one to the next release so that we can focus on getting Nepali date entry working on Collect and in the web app first.

**Comment by alxndrsn** [comment]
Due to #3404, bikram sambat date input in enketo forms should now work on android with numerical input fields using devanagari script.  Is this good enough?

**Comment by sglangevin** [comment]
@ranjuts will have to give the final sign-off but that sounds good to me!

**Comment by ranjuts** [comment]
Sounds good to me too!

**Comment by sglangevin** [comment]
Testing on Android, I'm still getting the normal Android date-picker (Gregorian calendar). Was I supposed to change the phone language to Nepali? Please advise on how to test this @alxndrsn.

**Comment by alxndrsn** [comment]
I'll look into this further!

**Comment by garethbowen** [comment]
Back to you @alxndrsn

**Comment by sglangevin** [comment]
@alxndrsn I've tested again and it's working fine in Chrome on desktop but not in the Android app (logged in as the same user on both). I'm using v0.2.3 of the Android container, maybe that's the issue? I've pushed v0.3.3 to the Play Store so that I can test there as well, but let me know if there is anything else to know when testing.

**Comment by alxndrsn** [comment]
Version of container shouldn't affect this feature.  Let me know which instance and which user you're testing with and I'll confirm the problem.

**Comment by sglangevin** [comment]
@alxndrsn it was standard.app, u: healthcenter, will DM you the password.

**Comment by alxndrsn** [comment]
Confirmed.

**Comment by alxndrsn** [comment]
This instance is not running the code from https://github.com/medic/medic-webapp/commit/27f5aba6de2cea06868b405d93404937736360c4

**Comment by sglangevin** [comment]
Does that code need to be backported to the 2.13.x branch? I was expecting it to be in beta.7 (or an earlier beta).

**Comment by sglangevin** [comment]
Working well on v2.13.0-beta.9. Moving to ready!
